### ISSUE TITLE
Please make a new hackage release

### ISSUE THREAD

**Issue by benma** [barrucadu/irc-client#1]
I just tried building this package from hackage, and compilation failed with some type mismatch regarding TimeLocale. I suspect that https://github.com/barrucadu/irc-client/commit/da564129fdb3773e163623f7f7a871c3d10f1168 fixes that, but that is not on hackage.

Thank you very much.

**Comment by barrucadu** [comment]
Alright, I'll address #2 and push a new release this weekend.

**Comment by barrucadu** [comment]
Version 0.2.4.0 pushed to hackage, see 50a7d66 for changes.
