### ISSUE TITLE
Client-side timeout

### ISSUE THREAD

**Issue by barrucadu** [barrucadu/irc-client#12]
Sometimes yukibot will drop off freenode, but the process will remain running. This means that network-conduit (or something) hasn't noticed the disconnect. A client-side timeout to initiate a disconnect if the server doesn't respond to a message in long enough would solve this.

**Comment by Profpatsch** [comment]
Have the same problem here. It just stops receiving messages.

Pretty much makes the library unusable. :(

**Comment by barrucadu** [comment]
Is this still a problem with the latest version of irc-client and irc-conduit? I don't think I've seen this behaviour since b0582d6, which got pushed to hackage in version 0.4.2.1.

**Comment by Profpatsch** [comment]
I had it a few times, yes. I tested the behaviour of `irc-conduit`, it doesn’t terminate when the socket doesn’t produce anything; since conduit can only be terminated by downstream pipes, that’s kind of obvious in hindsight. So yes, it should be possible to give `irc-client/irc-conduit` a timeout.

**Comment by siers** [comment]
I think I haven't seen it time out since I implemented a self-pinger.

https://github.com/siers/zn/blob/master/Main.hs#L64
https://github.com/siers/zn/blob/master/Zn/Pinger.hs

**Comment by barrucadu** [comment]
I believe 97a0dbe correctly implements this.

There is a new `_timeout` field of `ConnectionConfig`, which defaults to `300` (seconds) and can be set with the `timeout` lens. If nothing is received from the server for that period of time, the `Timeout` exception is thrown to the main thread, which interrupts the conduits and disconnects the client.
