### ISSUE TITLE
Unable to disconnect gracefully

### ISSUE THREAD

**Issue by JanGe** [barrucadu/irc-client#15]
Is there a way to gracefully disconnect?

* When I call [`disconnect`](https://github.com/barrucadu/irc-client/blob/master/Network/IRC/Client/Internal.hs#L196) from an event handler, the send queue gets closed resulting in the termination of the pipeline that is [handling the sending of the messages](https://github.com/barrucadu/irc-client/blob/master/Network/IRC/Client/Internal.hs#L98). The pipeline that is [logging and acting on incoming messages](https://github.com/barrucadu/irc-client/blob/master/Network/IRC/Client/Internal.hs#L99) continues running.

* Calling

        send $ Quit (Just "bye")

    results in an exception from [`exceptionalConduit`](https://github.com/barrucadu/irc-conduit/blob/master/Network/IRC/Conduit/Internal/Conduits.hs#L59) in the message decoding pipeline which then triggers a [call to `disconnect`](https://github.com/barrucadu/irc-client/blob/master/Network/IRC/Client/Internal.hs#L105) that is closing the send queue and terminating the other pipeline, but then ultimately rethrows the exception (which would also [kill all pipelines](https://github.com/barrucadu/irc-conduit/blob/master/Network/IRC/Conduit.hs#L172)).

One quick fix to make `disconnect` work would be to replace `awaitForever` with `await` and just not loop as soon as the send queue is closed. This then terminates the message decoding pipeline after receiving one further message.

    -- | Block on receiving a message and invoke all matching handlers
    -- concurrently.
    eventSink :: MonadIO m => IRCState s -> Consumer IrcEvent m ()
    eventSink ircstate = await >>= maybe (return ()) (\event -> do
      let event'  = decodeUtf8 <$> event
      ignored <- isIgnored ircstate event'
      unless ignored $ do
        handlers <- getHandlersFor event' . _eventHandlers <$> getInstanceConfig' ircstate
        liftIO $ mapM_ (\h -> forkIO $ runReaderT (h event') ircstate) handlers

      -- If no more events are expected, we can terminate this sink.
      disconnected <- isDisconnected ircstate
      unless disconnected $
        eventSink ircstate)

    -- | Check if the connection is already meant to be closed.
    isDisconnected :: MonadIO m => IRCState s -> m Bool
    isDisconnected ircstate = do
      let queueS  = _sendqueue $ getConnectionConfig ircstate
      liftIO . atomically $ isClosedTBMChan queueS

If you are fine with this approach, I can submit a PR. It probably would be cleaner to explicitly encode the state of the connection in `IRCState` though.

What do you think?

**Comment by barrucadu** [comment]
I agree that explicitly encoding the connection state would be better, I'll do that.
