### ISSUE TITLE
Event handler threads should get killed on disconnect.

### ISSUE THREAD

**Issue by barrucadu** [barrucadu/irc-client#39]
When the client disconnects, any event handler threads are left to run. They should be killed. Probably the easiest way to do this:

1. Have an `MVar [ThreadId]` in `IrcState`.
2. Have the forked thread in `eventSink` write its `ThreadId` to that list on start.
3. Have the forked thread in `eventSink` remove its `ThreadId` from that list on stop (with appropriate handling of an exception killing that thread).
4. Kill all remaining threads in `disconnect` (a new `Disconnected` exception, perhaps?)

**Comment by barrucadu** [comment]
Alternative solution: make handlers sequential, and provide a "managed fork" which ensures the thread is killed when the client disconnects, so people can opt in to concurrency if they want.

This also solves race conditions, and makes it easy to push uncaught exceptions in handlers up to the main thread.

**Comment by liyang** [comment]
I like the “managed fork” idea.

[`async`](http://hackage.haskell.org/package/async) might be useful here. I might have a stab at it… let me know if you're working on it too!

**Comment by barrucadu** [comment]
I think #40 is a good solution to this, any other ideas?

**Comment by barrucadu** [comment]
Closed by #40.
