### ISSUE TITLE
How do I trigger stuff after runner's initialise sends USER/NICK?

### ISSUE THREAD

**Issue by siers** [barrucadu/irc-client#9]
It looks like there's no event to be triggered. Maybe `instanceConfig >>= mapM_ (send . Join) . _channels` ought to be put in its own initHandler that you can then override and delegate to after/before your own code's been run? You could pass empty strings for `_raw`, `_message` and `_source`. 

There's also the option, albeit not a very attractive one, of dragging a `initCallback` argument from `start` to `runner`.

**Comment by barrucadu** [comment]
Yes, I think the best way to solve this would be to add an `_initHandler` field to `ConnectionConfig`

**Comment by barrucadu** [comment]
Sorry it took me *so long* to get around to actually doing this. Just pushed version 0.3.0.0 which splits out setting the nick and joining channels into its own connection handler (so only sending the `USER` command remains unchangeable).
